version: '2'
services:
  cli:
    image: thecodingmachine/php:8.1-v4-cli-node14
    command: bash
    volumes:
      - ./:/app
    user: ${MY_UID:-1000}
    tty: true
    working_dir: /app
    environment:
      PHP_EXTENSIONS: xdebug

